name: Pull Request - Validation

on:
  push:
    branches:
      - main

jobs:
  matrixed_job:
    name: Matrixed Job (${{ matrix.name }})
    uses: ./.github/workflows/callable.yml
    strategy:
      matrix:
        include:
          - name: Fail immediately
            sleep-secs: 0
            exit-code: 1
          - name: Succeed slowly
            sleep-secs: 10
            exit-code: 0
    with:
      sleep-secs: ${{ matrix.sleep-secs }}
      exit-code: ${{ matrix.exit-code }}

  print-result:
    name: Print Result
    needs: [matrixed_job]
    runs-on: ubuntu-latest
    if: always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
    steps:
      - name: Print Result
        run: |
          echo "Matrixed Job Result: ${{ needs.matrixed_job.result }}"
